ChartValues:
  server:
    service:
      type: LoadBalancer
    redis:
      master:
        persistence:
          storageClass: alicloud-disk-essd
          size: 40Gi
HelmChartPath: helm
RuntimeType: Kubernetes
OutputCmd: |-
  export SERVICE_IP=$(kubectl get svc --namespace ${Namespace} argo-cd-argocd-server -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
  echo "http://$SERVICE_IP/"
ServiceType: private
ArtifactSourceType: HelmChart
ServiceBuildRegion: ap-southeast-1
RepoName: aliyun-computenest/quickstart-argocd
RegionId: cn-hangzhou
OutputType: OutputCommand
Owner: linziqiaolzq
Branch: main
Platform: github
