Service:
  RegionId: cn-hangzhou
  DeployType: ros
  DeployMetadata:
    ServiceInstanceNameRule:
      Prefix: argocd-
    SupplierDeployMetadata:
      HelmChartArtifactRelation:
        '{{ computenest::helmchart::argocd }}':
          ArtifactId: ${Artifact.Artifact_HelmChart_ArgoCD.ArtifactId}
          ArtifactVersion: ${Artifact.Artifact_HelmChart_ArgoCD.ArtifactVersion}
    TemplateConfigs:
      - Name: 模版1
        Url: 'ros_templates/template.yaml'
        AllowedRegions: []
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: Argo CD 是一个用于 Kubernetes 的声明式、GitOps 持续交付工具。它通过将应用程序配置存储在 Git 仓库中，并自动将应用程序部署到 Kubernetes 集群来实现持续交付。
    Image: 'resources/icons/service_logo.png'
    Name: ArgoCD社区版
  ShareType: Public
  ApprovalType: Manual
Artifact:
  Artifact_HelmChart_ArgoCD:
    ArtifactType: HelmChart
    ArtifactName: Chart_ArgoCD
    Description: ArgoCD HelmChart部署物
    ArtifactProperty:
      RepoName: ${HelmChartBuilder.HelmChart_ArgoCD.RepoName}
      Tag: ${HelmChartBuilder.HelmChart_ArgoCD.Tag}
HelmChartBuilder:
  HelmChart_ArgoCD:
    HelmChartPath: '../targets/argo-cd-7.7.8.tgz'
    RepoName: argo-cd
    Tag: 7.7.8